# Generated by Django 2.0.7 on 2018-08-08 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=50)),
                ('ApellidoPaterno', models.CharField(max_length=35)),
                ('ApellidoMaterno', models.CharField(max_length=35)),
                ('Ci', models.CharField(max_length=10)),
                ('FehaDesaparicion', models.DateField()),
                ('FehaRegistro', models.DateField(auto_now_add=True)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('Direccion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=False)),
                ('Edad', models.IntegerField()),
                ('Estatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Descripcion', models.TextField(max_length=200)),
                ('Contextura', models.CharField(choices=[('D', 'Delgada'), ('M', 'Mediana'), ('S', 'Semigruesa'), ('G', 'Gruesa')], default='D', max_length=5)),
                ('Contexrura', models.CharField(choices=[('C', 'Clara'), ('T', 'Trigueña'), ('M', 'Morena')], default='C', max_length=5)),
                ('Cabello', models.CharField(choices=[('N', 'Negro'), ('B', 'Blanco'), ('C', 'Cafe'), ('R', 'Rojo'), ('RU', 'Rubio')], default='N', max_length=5)),
                ('Ojos', models.CharField(choices=[('N', 'Negro'), ('V', 'Verde'), ('C', 'Cafe'), ('CE', 'Celeste')], default='N', max_length=5)),
                ('usuario', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='face',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recog.Person'),
        ),
    ]
