# Generated by Django 2.0.7 on 2018-08-17 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
