# Generated by Django 2.0.7 on 2018-08-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0002_auto_20180817_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='activo',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Contexrura',
            new_name='Tez',
        ),
    ]
