# Generated by Django 2.1.1 on 2018-09-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0007_auto_20180905_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='institucion',
            new_name='inst',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
