# Generated by Django 2.1.1 on 2018-09-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0008_auto_20180905_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='inst',
            new_name='institucion',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user',
        ),
    ]
