# Generated by Django 2.1.1 on 2018-09-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0014_auto_20180908_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['FehaRegistro']},
        ),
    ]
