# Generated by Django 2.1.1 on 2018-09-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0015_auto_20180908_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-FehaRegistro']},
        ),
    ]
