# Generated by Django 2.1.1 on 2018-09-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0023_auto_20180912_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personphoto',
            name='persona',
        ),
        migrations.AddField(
            model_name='person',
            name='faceData',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='facePicture',
            field=models.FileField(max_length=255, null=True, upload_to='faces'),
        ),
        migrations.DeleteModel(
            name='Personphoto',
        ),
    ]
