# Generated by Django 2.1.1 on 2018-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0024_auto_20180927_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='facePicture',
            field=models.ImageField(max_length=255, null=True, upload_to='faces'),
        ),
    ]
