# Generated by Django 2.1.1 on 2018-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0025_auto_20180928_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='referencia',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profesion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='facePicture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='faces/%m/%d/%Y'),
        ),
    ]
