# Generated by Django 2.1.1 on 2018-10-04 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0026_auto_20181001_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Ci',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
