# Generated by Django 2.1.1 on 2018-10-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0029_auto_20181010_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ApellidoPaterno',
            field=models.CharField(blank=True, help_text='Introduzca un apellido correcto', max_length=35, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Descripcion',
            field=models.TextField(max_length=200, null=True, verbose_name='Descripción de la Desaparición '),
        ),
        migrations.AlterField(
            model_name='person',
            name='Edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='FehaDesaparicion',
            field=models.DateField(null=True, verbose_name='Desaparecio en Fecha:'),
        ),
    ]
