# Generated by Django 2.1.1 on 2018-10-23 08:04

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0030_auto_20181011_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '700x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='person',
            name='facePicture',
            field=models.ImageField(help_text='La imagen debe contener una Persona.', max_length=255, null=True, upload_to='faces/%m/%d/%Y', verbose_name='Dirección'),
        ),
    ]
