# Generated by Django 2.1.1 on 2018-10-23 08:16

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0031_auto_20181023_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('facePicture', '700x500', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
