# Generated by Django 2.1.1 on 2018-11-30 02:57

import django.core.validators
from django.db import migrations, models
import recog.helper


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0033_remove_person_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Edad',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='facePicture',
            field=models.ImageField(help_text='La imagen debe contener una Persona.', max_length=255, null=True, upload_to='faces/%m/%d/%Y', validators=[recog.helper.face_detection], verbose_name='Dirección'),
        ),
    ]
